[package]
name = "dnssector"
version = "0.1.0"
authors = ["Frank Denis <github@pureftpd.org>"]

[dependencies]
byteorder = "*"
chomp = "*"
clippy = {version = "~0", optional = true}
debug_stub_derive = "*"
failure = "*"
failure_derive = "*"
libc = "*"
libloading = "*"
xfailure = "*"

[profile.release]
lto = true
panic = "abort"
opt-level = 3
