[package]
name = "dnssector"
version = "0.1.0"
authors = ["Frank Denis <github@pureftpd.org>"]

[dependencies]
clippy = {version = "~0", optional = true}
byteorder = "*"
debug_stub_derive = "*"
error-chain = "*"
libc = "*"
libloading = "*"
