[package]
name = "dnssector"
version = "0.1.0"
authors = ["Frank Denis <github@pureftpd.org>"]

[dependencies]
clippy = {version = "~0", optional = true}
byteorder = "*"
chomp = "*"
debug_stub_derive = "*"
libc = "*"
libloading = "*"
error-chain = {version = "*", default-features = false}

[profile.release]
lto = true
panic = "abort"
opt-level = 3
